name: Build Android APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04 # تحديد نسخة مستقرة من لينكس

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          # تثبيت Cython المتوافق وتحديث أدوات البناء
          pip3 install --user --upgrade Cython==0.29.33 virtualenv setuptools
          export PATH=$PATH:$HOME/.local/bin

      - name: Build with Buildozer
        run: |
          export PATH=$PATH:$HOME/.local/bin
          # قبول التراخيص آلياً وحذف أي بقايا بناء قديم
          rm -rf .buildozer
          yes | buildozer android debug
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: HomeStore-APK
          path: bin/*.apk
