name: Build Android APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          # تثبيت المتطلبات والتأكد من تحديث pip
          python3 -m pip install --user --upgrade pip
          python3 -m pip install --user --upgrade Cython==0.29.33 virtualenv setuptools buildozer

      - name: Build with Buildozer
        run: |
          # إضافة المسار يدوياً لضمان التعرف على الأوامر
          export PATH=$PATH:$HOME/.local/bin
          # استخدام 'python3 -m buildozer' بدلاً من 'buildozer' مباشرة لتجنب خطأ 127
          yes | python3 -m buildozer android debug
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: HomeStore-APK
          path: bin/*.apk
